spring.application.name=contable-api

# Base de datos (Usamos variables que inyectaremos luego)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/guida_contable}
spring.datasource.username=${DB_USER:guida_user}
spring.datasource.password=${DB_PASSWORD:password123}

# Configuracion AFIP
afip.cert.path=${AFIP_CERT_PATH:certs/certificado.p12}
afip.cert.password=${AFIP_CERT_PASSWORD}
afip.signer=${AFIP_SIGNER:guida-alias}