spring.application.name=invoice-service
server.port=8083

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/guida_contable}
spring.datasource.username=${DB_USER:guida_user}
spring.datasource.password=${DB_PASSWORD:password123}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.datasource.hikari.initialization-fail-timeout=-1

# URLs de servicios internos
services.afip-service.url=${AFIP_SERVICE_URL:http://afip-service:8084}
