spring.application.name=mp-service
server.port=8089

auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}
ledger-service.url=${LEDGER_SERVICE_URL:http://localhost:8088}
internal-api-key=${INTERNAL_API_KEY:}

mp.base-url=https://api.mercadopago.com
notification-service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8090}
